# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, 'friends'), (1, 'family'), (2, 'colleagues_from_work')])),
                ('description', models.TextField()),
                ('person', models.ManyToManyField(to='my_app.Person')),
            ],
        ),
    ]
