# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
