# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20171031_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.IntegerField(choices=[(0, 'permanent'), (1, 'of_residence'), (2, 'for_correspondence')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_type',
            field=models.IntegerField(choices=[(0, 'home'), (1, 'mobile'), (2, 'business')]),
        ),
    ]
