# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20171101_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_number',
            field=models.CharField(max_length=16),
        ),
    ]
